"""Champs BT du mapping Réforme Factur-X (EN16931) — seeding initial."""

_H = "/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/"
_AGR = _H + "ram:ApplicableHeaderTradeAgreement/"
_SET = _H + "ram:ApplicableHeaderTradeSettlement/"
_DEL = _H + "ram:ApplicableHeaderTradeDelivery/"
_LINE = _H + "ram:IncludedSupplyChainTradeLineItem/"
_DOC = "/rsm:CrossIndustryInvoice/rsm:ExchangedDocument/"
_CTX = "/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext/"

def _c(balise, libelle, xpath, obligatoire, type_="String", rdg="",
       categorie_bg="", categorie_titre="", attribute="", is_article=False):
    d = {
        "balise": balise, "libelle": libelle, "rdi": "", "xpath": xpath,
        "type": type_, "obligatoire": obligatoire, "ignore": "Non",
        "rdg": rdg, "categorie_bg": categorie_bg,
        "categorie_titre": categorie_titre, "valide": True,
        "controles_cegedim": [],
    }
    if attribute:
        d["attribute"] = attribute
    if is_article:
        d["is_article"] = True
    return d

_BG0 = ("BG-PROCESSUS", "CONTEXTE ET PROFIL")
_BG1 = ("BG-INFOS-GENERALES", "INFORMATIONS GÉNÉRALES DE LA FACTURE")
_BGNOTES = ("BG-NOTES", "NOTES DE FACTURE")
_BGAVOIR = ("BG-AVOIR", "FACTURE ANTÉRIEURE (AVOIR)")
_BGVEND = ("BG-VENDEUR", "INFORMATIONS VENDEUR")
_BGACH = ("BG-ACHETEUR", "INFORMATIONS ACHETEUR")
_BGBENEF = ("BG-BENEFICIAIRE", "BÉNÉFICIAIRE")
_BGREP = ("BG-REP-FISCAL", "REPRÉSENTANT FISCAL")
_BGLIV = ("BG-LIVRAISON", "INFORMATIONS DE LIVRAISON")
_BGREG = ("BG-REGLEMENT", "INSTRUCTIONS DE RÈGLEMENT")
_BGREM = ("BG-REMISES-DOC", "REMISES NIVEAU DOCUMENT")
_BGFRAIS = ("BG-FRAIS-DOC", "FRAIS NIVEAU DOCUMENT")
_BGTOT = ("BG-TOTAUX", "TOTAUX DE LA FACTURE")
_BGTVA = ("BG-TVA", "VENTILATION DE LA TVA")
_BGPJ = ("BG-PIECES-JOINTES", "PIÈCES JUSTIFICATIVES")
_BGLIG = ("BG-LIGNES", "LIGNES DE FACTURE")

_REFORME_CHAMPS = [
    # ── Contexte et profil ───────────────────────────────────────────────────
    _c("BT-23", "Identifiant du processus métier",
       _CTX + "ram:BusinessProcessSpecifiedDocumentContextParameter/ram:ID",
       "Non", rdg="Ex. : urn:factur-x.eu:1p0:minimum",
       categorie_bg=_BG0[0], categorie_titre=_BG0[1]),
    _c("BT-24", "Identifiant de profil Factur-X",
       _CTX + "ram:GuidelineSpecifiedDocumentContextParameter/ram:ID",
       "Oui", rdg="Ex. : urn:factur-x.eu:1p0:en16931",
       categorie_bg=_BG0[0], categorie_titre=_BG0[1]),

    # ── Informations générales ───────────────────────────────────────────────
    _c("BT-1", "Numéro de la facture",
       _DOC + "ram:ID",
       "Oui", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-2", "Date d'émission de la facture",
       _DOC + "ram:IssueDateTime/udt:DateTimeString",
       "Oui", type_="Date", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-3", "Code type de facture",
       _DOC + "ram:TypeCode",
       "Oui", rdg="380 = Facture · 381 = Avoir · 386 = Acompte",
       categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-5", "Code devise de la facture",
       _SET + "ram:InvoiceCurrencyCode",
       "Oui", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-6", "Code devise comptable TVA",
       _SET + "ram:TaxCurrencyCode",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-7", "Date du point de TVA",
       _SET + "ram:ApplicableTradeTax/ram:TaxPointDate/udt:DateString",
       "Non", type_="Date", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-8", "Code de date du point de TVA",
       _SET + "ram:ApplicableTradeTax/ram:DueDateTypeCode",
       "Non", rdg="Valeur attendue : 5",
       categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-9", "Date d'échéance de paiement",
       _SET + "ram:SpecifiedTradePaymentTerms/ram:DueDateDateTime/udt:DateTimeString",
       "Non", type_="Date", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-10", "Référence acheteur (Chorus Pro)",
       _AGR + "ram:BuyerReference",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-11", "Référence projet",
       _AGR + "ram:SpecifiedProcuringProject/ram:ID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-12", "Référence contrat",
       _AGR + "ram:ContractReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-13", "Référence commande acheteur",
       _AGR + "ram:BuyerOrderReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-14", "Référence commande vendeur",
       _AGR + "ram:SellerOrderReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-15", "Référence bon de réception",
       _DEL + "ram:ReceivingAdviceReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-16", "Référence avis d'expédition",
       _DEL + "ram:DespatchAdviceReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-17", "Référence appel d'offres / lot",
       _AGR + "ram:AdditionalReferencedDocument[ram:TypeCode='50']/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-18", "Référence objet facturé",
       _AGR + "ram:AdditionalReferencedDocument[ram:TypeCode='130']/ram:IssuerAssignedID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-19", "Référence comptable acheteur",
       _AGR + "ram:ReceivablesAccountantTradeParty/ram:ID",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),
    _c("BT-20", "Conditions de paiement (texte)",
       _SET + "ram:SpecifiedTradePaymentTerms/ram:Description",
       "Non", categorie_bg=_BG1[0], categorie_titre=_BG1[1]),

    # ── Notes de facture (BG-1) ──────────────────────────────────────────────
    _c("BT-21-BAR", "Code mention « Traitement attendu »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='BAR']/ram:SubjectCode",
       "Oui", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-BAR", "Mention « Traitement attendu » (B2B/B2BINT/B2G)",
       _DOC + "ram:IncludedNote[ram:SubjectCode='BAR']/ram:Content",
       "Oui", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-21-SUR", "Code mention « Remarques fournisseur »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='SUR']/ram:SubjectCode",
       "Oui", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-SUR", "Remarques fournisseur (valeur : ISU)",
       _DOC + "ram:IncludedNote[ram:SubjectCode='SUR']/ram:Content",
       "Oui", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-21-ADN", "Code mention « B2G France Chorus »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='ADN']/ram:SubjectCode",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-ADN", "Mention « B2G France Chorus »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='ADN']/ram:Content",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-21-AAB", "Code mention « Escompte »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='AAB']/ram:SubjectCode",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-AAB", "Mention « Escompte »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='AAB']/ram:Content",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-21-PMT", "Code mention « Indemnité 40 € »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='PMT']/ram:SubjectCode",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-PMT", "Mention « Indemnité forfaitaire de recouvrement »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='PMT']/ram:Content",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-21-PMD", "Code mention « Pénalités »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='PMD']/ram:SubjectCode",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),
    _c("BT-22-PMD", "Mention « Pénalités de retard »",
       _DOC + "ram:IncludedNote[ram:SubjectCode='PMD']/ram:Content",
       "Non", categorie_bg=_BGNOTES[0], categorie_titre=_BGNOTES[1]),

    # ── Facture antérieure (BG-3) ────────────────────────────────────────────
    _c("BT-25", "Référence à la facture antérieure",
       _SET + "ram:InvoiceReferencedDocument/ram:IssuerAssignedID",
       "Non", rdg="Obligatoire sur avoir (BT-3 = 381)",
       categorie_bg=_BGAVOIR[0], categorie_titre=_BGAVOIR[1]),
    _c("BT-26", "Date d'émission de la facture antérieure",
       _SET + "ram:InvoiceReferencedDocument/ram:FormattedIssueDateTime/qdt:DateTimeString",
       "Non", type_="Date", rdg="Obligatoire sur avoir (BT-3 = 381)",
       categorie_bg=_BGAVOIR[0], categorie_titre=_BGAVOIR[1]),

    # ── Vendeur (BG-4 + BG-5 + BG-6) ────────────────────────────────────────
    _c("BT-27", "Raison sociale du vendeur",
       _AGR + "ram:SellerTradeParty/ram:Name",
       "Oui", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-28", "Enseigne commerciale du vendeur",
       _AGR + "ram:SellerTradeParty/ram:SpecifiedLegalOrganization/ram:TradingBusinessName",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-29", "Identifiant du vendeur",
       _AGR + "ram:SellerTradeParty/ram:ID",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-29-1", "Schéma identifiant vendeur",
       _AGR + "ram:SellerTradeParty/ram:ID",
       "Non", attribute="schemeID",
       categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-30", "SIREN du vendeur",
       _AGR + "ram:SellerTradeParty/ram:SpecifiedLegalOrganization/ram:ID",
       "Oui", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-30-1", "Schéma SIREN vendeur",
       _AGR + "ram:SellerTradeParty/ram:SpecifiedLegalOrganization/ram:ID",
       "Oui", attribute="schemeID",
       categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-31", "N° TVA intracommunautaire du vendeur",
       _AGR + "ram:SellerTradeParty/ram:SpecifiedTaxRegistration[ram:ID/@schemeID='VA']/ram:ID",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-32", "Identifiant fiscal du vendeur",
       _AGR + "ram:SellerTradeParty/ram:SpecifiedTaxRegistration[ram:ID/@schemeID='FC']/ram:ID",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-33", "Informations légales complémentaires vendeur",
       _AGR + "ram:SellerTradeParty/ram:Description",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-34", "Adresse électronique du vendeur",
       _AGR + "ram:SellerTradeParty/ram:URIUniversalCommunication/ram:URIID",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-35", "Adresse vendeur – Ligne 1",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:LineOne",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-36", "Adresse vendeur – Ligne 2",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:LineTwo",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-37", "Adresse vendeur – Ligne 3",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:LineThree",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-38", "Ville du vendeur",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:CityName",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-39", "Code postal du vendeur",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:PostcodeCode",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-40", "Code pays du vendeur",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:CountryID",
       "Oui", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-41", "Région / département du vendeur",
       _AGR + "ram:SellerTradeParty/ram:PostalTradeAddress/ram:CountrySubDivisionName",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-41a", "Contact vendeur",
       _AGR + "ram:SellerTradeParty/ram:DefinedTradeContact/ram:PersonName",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-42", "Téléphone contact vendeur",
       _AGR + "ram:SellerTradeParty/ram:DefinedTradeContact/ram:TelephoneUniversalCommunication/ram:CompleteNumber",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),
    _c("BT-43", "Email contact vendeur",
       _AGR + "ram:SellerTradeParty/ram:DefinedTradeContact/ram:EmailURIUniversalCommunication/ram:URIID",
       "Non", categorie_bg=_BGVEND[0], categorie_titre=_BGVEND[1]),

    # ── Acheteur (BG-7 + BG-8 + BG-9) ──────────────────────────────────────
    _c("BT-44", "Raison sociale de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:Name",
       "Oui", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-45", "Enseigne commerciale de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:SpecifiedLegalOrganization/ram:TradingBusinessName",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-46", "Identifiant de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:ID",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-47", "SIREN de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:SpecifiedLegalOrganization/ram:ID",
       "Oui", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-47-1", "Schéma SIREN acheteur",
       _AGR + "ram:BuyerTradeParty/ram:SpecifiedLegalOrganization/ram:ID",
       "Oui", attribute="schemeID",
       categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-48", "N° TVA intracommunautaire de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:SpecifiedTaxRegistration[ram:ID/@schemeID='VA']/ram:ID",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-49", "Identifiant d'adressage de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:URIUniversalCommunication/ram:URIID",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-49-1", "Schéma identifiant d'adressage acheteur",
       _AGR + "ram:BuyerTradeParty/ram:URIUniversalCommunication/ram:URIID",
       "Non", attribute="schemeID",
       categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-50", "Adresse acheteur – Ligne 1",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:LineOne",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-51", "Adresse acheteur – Ligne 2",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:LineTwo",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-52", "Ville de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:CityName",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-53", "Code postal de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:PostcodeCode",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-54", "Région / département de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:CountrySubDivisionName",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-55", "Code pays de l'acheteur",
       _AGR + "ram:BuyerTradeParty/ram:PostalTradeAddress/ram:CountryID",
       "Oui", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-56", "Contact acheteur",
       _AGR + "ram:BuyerTradeParty/ram:DefinedTradeContact/ram:PersonName",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-57", "Téléphone contact acheteur",
       _AGR + "ram:BuyerTradeParty/ram:DefinedTradeContact/ram:TelephoneUniversalCommunication/ram:CompleteNumber",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),
    _c("BT-58", "Email contact acheteur",
       _AGR + "ram:BuyerTradeParty/ram:DefinedTradeContact/ram:EmailURIUniversalCommunication/ram:URIID",
       "Non", categorie_bg=_BGACH[0], categorie_titre=_BGACH[1]),

    # ── Bénéficiaire (BG-10) ─────────────────────────────────────────────────
    _c("BT-59", "Raison sociale du bénéficiaire",
       _SET + "ram:PayeeTradeParty/ram:Name",
       "Non", categorie_bg=_BGBENEF[0], categorie_titre=_BGBENEF[1]),
    _c("BT-60", "Identifiant du bénéficiaire",
       _SET + "ram:PayeeTradeParty/ram:ID",
       "Non", categorie_bg=_BGBENEF[0], categorie_titre=_BGBENEF[1]),
    _c("BT-61", "SIREN du bénéficiaire",
       _SET + "ram:PayeeTradeParty/ram:SpecifiedLegalOrganization/ram:ID",
       "Non", categorie_bg=_BGBENEF[0], categorie_titre=_BGBENEF[1]),

    # ── Représentant fiscal (BG-11 + BG-12) ─────────────────────────────────
    _c("BT-62", "Nom du représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:Name",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-63", "N° TVA du représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:SpecifiedTaxRegistration/ram:ID",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-64", "Adresse représentant fiscal – Ligne 1",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:LineOne",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-65", "Adresse représentant fiscal – Ligne 2",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:LineTwo",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-66", "Ville représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:CityName",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-67", "Code postal représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:PostcodeCode",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-68", "Région représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:CountrySubDivisionName",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),
    _c("BT-69", "Code pays représentant fiscal",
       _AGR + "ram:SellerTaxRepresentativeTradeParty/ram:PostalTradeAddress/ram:CountryID",
       "Non", categorie_bg=_BGREP[0], categorie_titre=_BGREP[1]),

    # ── Livraison (BG-13 + BG-14 + BG-15) ───────────────────────────────────
    _c("BT-70", "Destinataire de la livraison",
       _DEL + "ram:ShipToTradeParty/ram:Name",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-71", "Identifiant du lieu de livraison",
       _DEL + "ram:ShipToTradeParty/ram:ID",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-72", "Date de livraison effective",
       _DEL + "ram:ActualDeliverySupplyChainEvent/ram:OccurrenceDateTime/udt:DateTimeString",
       "Non", type_="Date", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-73", "Début de période de facturation",
       _SET + "ram:BillingSpecifiedPeriod/ram:StartDateTime/udt:DateTimeString",
       "Non", type_="Date", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-74", "Fin de période de facturation",
       _SET + "ram:BillingSpecifiedPeriod/ram:EndDateTime/udt:DateTimeString",
       "Non", type_="Date", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-75", "Adresse livraison – Ligne 1",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:LineOne",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-76", "Adresse livraison – Ligne 2",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:LineTwo",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-77", "Ville de livraison",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:CityName",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-78", "Code postal de livraison",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:PostcodeCode",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-79", "Région de livraison",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:CountrySubDivisionName",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),
    _c("BT-80", "Code pays de livraison",
       _DEL + "ram:ShipToTradeParty/ram:PostalTradeAddress/ram:CountryID",
       "Non", categorie_bg=_BGLIV[0], categorie_titre=_BGLIV[1]),

    # ── Règlement (BG-16 à BG-19) ────────────────────────────────────────────
    _c("BT-81", "Code moyen de paiement",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:TypeCode",
       "Oui", rdg="30=Virement · 31=Prélèvement · 48=Carte · 49=SEPA",
       categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-82", "Texte du moyen de paiement",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:Information",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-83", "Référence de remise",
       _SET + "ram:PaymentReference",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-84", "IBAN du compte créditeur",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount/ram:IBANID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-85", "Nom du titulaire du compte",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeePartyCreditorFinancialAccount/ram:AccountName",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-86", "BIC de la banque créditrice",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:PayeeSpecifiedCreditorFinancialInstitution/ram:BICID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-87", "N° de carte bancaire",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:ApplicableTradeSettlementFinancialCard/ram:ID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-88", "Nom du porteur de carte",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:ApplicableTradeSettlementFinancialCard/ram:CardholderName",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-89", "Référence mandat de prélèvement",
       _SET + "ram:SpecifiedTradePaymentTerms/ram:DirectDebitMandateID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-90", "Identifiant créancier SEPA",
       _SET + "ram:CreditorReferenceID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),
    _c("BT-91", "IBAN du compte débité",
       _SET + "ram:SpecifiedTradeSettlementPaymentMeans/ram:PayerPartyDebtorFinancialAccount/ram:IBANID",
       "Non", categorie_bg=_BGREG[0], categorie_titre=_BGREG[1]),

    # ── Remises niveau document (BG-20) ──────────────────────────────────────
    _c("BT-92", "Montant de remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:ActualAmount",
       "Non", type_="Decimal", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-93", "Base de calcul remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:BasisAmount",
       "Non", type_="Decimal", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-94", "Pourcentage de remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:CalculationPercent",
       "Non", type_="Decimal", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-95", "Code catégorie TVA – remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:CategoryTradeTax/ram:CategoryCode",
       "Non", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-96", "Taux TVA – remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:CategoryTradeTax/ram:RateApplicablePercent",
       "Non", type_="Decimal", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-97", "Motif de remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:Reason",
       "Non", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),
    _c("BT-98", "Code motif de remise document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:ReasonCode",
       "Non", categorie_bg=_BGREM[0], categorie_titre=_BGREM[1]),

    # ── Frais niveau document (BG-21) ─────────────────────────────────────────
    _c("BT-99", "Montant de frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:ActualAmount",
       "Non", type_="Decimal", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-100", "Base de calcul frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:BasisAmount",
       "Non", type_="Decimal", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-101", "Pourcentage de frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:CalculationPercent",
       "Non", type_="Decimal", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-102", "Code catégorie TVA – frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:CategoryTradeTax/ram:CategoryCode",
       "Non", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-103", "Taux TVA – frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:CategoryTradeTax/ram:RateApplicablePercent",
       "Non", type_="Decimal", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-104", "Motif de frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:Reason",
       "Non", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),
    _c("BT-105", "Code motif de frais document",
       _SET + "ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:ReasonCode",
       "Non", categorie_bg=_BGFRAIS[0], categorie_titre=_BGFRAIS[1]),

    # ── Totaux (BG-22) ───────────────────────────────────────────────────────
    _c("BT-106", "Somme des montants nets des lignes",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:LineTotalAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-107", "Total des remises niveau document",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:AllowanceTotalAmount",
       "Non", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-108", "Total des frais niveau document",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:ChargeTotalAmount",
       "Non", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-109", "Montant total HT de la facture",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TaxBasisTotalAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-110", "Montant total de TVA de la facture",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TaxTotalAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-111", "Montant total de TVA en devise comptable",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TaxTotalAmount[@currencyID]",
       "Non", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-112", "Montant total TTC de la facture",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:GrandTotalAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-113", "Montant déjà payé / acompte",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:TotalPrepaidAmount",
       "Non", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-114", "Montant d'arrondi",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:RoundingAmount",
       "Non", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),
    _c("BT-115", "Montant à payer",
       _SET + "ram:SpecifiedTradeSettlementHeaderMonetarySummation/ram:DuePayableAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTOT[0], categorie_titre=_BGTOT[1]),

    # ── Ventilation TVA (BG-23) ──────────────────────────────────────────────
    _c("BT-116", "Base imposable par catégorie de TVA",
       _SET + "ram:ApplicableTradeTax/ram:BasisAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),
    _c("BT-117", "Montant de TVA par catégorie",
       _SET + "ram:ApplicableTradeTax/ram:CalculatedAmount",
       "Oui", type_="Decimal", categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),
    _c("BT-118", "Code catégorie de TVA",
       _SET + "ram:ApplicableTradeTax/ram:CategoryCode",
       "Oui", rdg="S=Standard · Z=Taux zéro · E=Exonéré · AE=Autoliquidation · K=Intra-UE · G=Export · O=Hors champ",
       categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),
    _c("BT-119", "Taux de TVA",
       _SET + "ram:ApplicableTradeTax/ram:RateApplicablePercent",
       "Non", type_="Decimal", categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),
    _c("BT-120", "Motif d'exonération de TVA (texte)",
       _SET + "ram:ApplicableTradeTax/ram:ExemptionReason",
       "Non", categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),
    _c("BT-121", "Code motif d'exonération de TVA",
       _SET + "ram:ApplicableTradeTax/ram:ExemptionReasonCode",
       "Non", categorie_bg=_BGTVA[0], categorie_titre=_BGTVA[1]),

    # ── Pièces justificatives (BG-24) ────────────────────────────────────────
    _c("BT-122", "Référence pièce justificative",
       _AGR + "ram:AdditionalReferencedDocument/ram:IssuerAssignedID",
       "Non", categorie_bg=_BGPJ[0], categorie_titre=_BGPJ[1]),
    _c("BT-123", "Description pièce justificative",
       _AGR + "ram:AdditionalReferencedDocument/ram:Name",
       "Non", categorie_bg=_BGPJ[0], categorie_titre=_BGPJ[1]),
    _c("BT-124", "URL pièce jointe externe",
       _AGR + "ram:AdditionalReferencedDocument/ram:URIID",
       "Non", categorie_bg=_BGPJ[0], categorie_titre=_BGPJ[1]),
    _c("BT-125", "Contenu de la pièce jointe (base64)",
       _AGR + "ram:AdditionalReferencedDocument/ram:AttachmentBinaryObject",
       "Non", categorie_bg=_BGPJ[0], categorie_titre=_BGPJ[1]),

    # ── Lignes de facture (BG-25 à BG-32) ───────────────────────────────────
    _c("BT-126", "Identifiant de ligne",
       _LINE + "ram:AssociatedDocumentLineDocument/ram:LineID",
       "Oui", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-127", "Note de ligne",
       _LINE + "ram:AssociatedDocumentLineDocument/ram:IncludedNote/ram:Content",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-128", "Identifiant de l'objet facturé (ligne)",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:AdditionalReferencedDocument/ram:IssuerAssignedID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-129", "Quantité facturée",
       _LINE + "ram:SpecifiedLineTradeDelivery/ram:BilledQuantity",
       "Oui", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-130", "Code unité de mesure",
       _LINE + "ram:SpecifiedLineTradeDelivery/ram:BilledQuantity",
       "Oui", attribute="unitCode", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-131", "Montant net de la ligne",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeSettlementLineMonetarySummation/ram:LineTotalAmount",
       "Oui", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-132", "Référence ligne commande acheteur",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:BuyerOrderReferencedDocument/ram:LineID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-133", "Référence comptable acheteur (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:ReceivableSpecifiedTradeAccountingAccount/ram:ID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-134", "Début de période de facturation (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:BillingSpecifiedPeriod/ram:StartDateTime/udt:DateTimeString",
       "Non", type_="Date", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-135", "Fin de période de facturation (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:BillingSpecifiedPeriod/ram:EndDateTime/udt:DateTimeString",
       "Non", type_="Date", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-136", "Montant de remise (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:ActualAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-137", "Base de calcul remise (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:BasisAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-138", "Pourcentage remise (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:CalculationPercent",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-139", "Motif de remise (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:Reason",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-140", "Code motif de remise (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='false']/ram:ReasonCode",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-141", "Montant de frais (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:ActualAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-142", "Base de calcul frais (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:BasisAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-143", "Pourcentage frais (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:CalculationPercent",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-144", "Motif de frais (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:Reason",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-145", "Code motif de frais (ligne)",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:SpecifiedTradeAllowanceCharge[ram:ChargeIndicator/udt:Indicator='true']/ram:ReasonCode",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-146", "Prix net unitaire de l'article",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:NetPriceProductTradePrice/ram:ChargeAmount",
       "Oui", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-147", "Remise sur prix brut",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:AppliedTradeAllowanceCharge/ram:ActualAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-148", "Prix brut unitaire de l'article",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:ChargeAmount",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-149", "Quantité de base pour le prix",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:NetPriceProductTradePrice/ram:BasisQuantity",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-150", "Code unité de la quantité de base",
       _LINE + "ram:SpecifiedLineTradeAgreement/ram:NetPriceProductTradePrice/ram:BasisQuantity",
       "Non", attribute="unitCode", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-151", "Code catégorie TVA de l'article",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:ApplicableTradeTax/ram:CategoryCode",
       "Oui", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-152", "Taux de TVA de l'article",
       _LINE + "ram:SpecifiedLineTradeSettlement/ram:ApplicableTradeTax/ram:RateApplicablePercent",
       "Non", type_="Decimal", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-153", "Nom de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:Name",
       "Oui", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-154", "Description de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:Description",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-155", "Référence article vendeur",
       _LINE + "ram:SpecifiedTradeProduct/ram:SellerAssignedID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-156", "Référence article acheteur",
       _LINE + "ram:SpecifiedTradeProduct/ram:BuyerAssignedID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-157", "Identifiant standard de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:GlobalID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-158", "Identifiant de classification de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:DesignatedProductClassification/ram:ClassCode",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-159", "Code pays d'origine de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:OriginTradeCountry/ram:ID",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-160", "Nom d'attribut de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:ApplicableProductCharacteristic/ram:Description",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
    _c("BT-161", "Valeur d'attribut de l'article",
       _LINE + "ram:SpecifiedTradeProduct/ram:ApplicableProductCharacteristic/ram:Value",
       "Non", is_article=True, categorie_bg=_BGLIG[0], categorie_titre=_BGLIG[1]),
]
